version: '3.7'
services:
  agixt-interactive:
    image: ghcr.io/jamesonrgrieve/agixt-interactive:main
    init: true
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - APP_NAME=${APP_NAME-AGiXT Interactive}
      - APP_DESCRIPTION=${APP_DESCRIPTION-Interactive interface for AGiXT.}
      - APP_URI=${APP_URI-http://localhost:3437}
      - AUTH_WEB=${AUTH_WEB-http://localhost:3437/user}
      - ALLOW_EMAIL_SIGN_IN=${ALLOW_EMAIL_SIGN_IN}
      - LOG_VERBOSITY_SERVER=${LOG_VERBOSITY_SERVER-3}
      - THEME_NAME=${THEME_NAME-valentines}
      - DEFAULT_THEME_MODE=${DEFAULT_THEME_MODE}
      - ENV=${ENV-production}
      - TZ=${TZ-America/New_York}
      - AGIXT_SERVER=${AGIXT_SERVER-http://localhost:7437}
      - AGIXT_API_KEY=${AGIXT_API_KEY}
      - AGIXT_MODE=${AGIXT_MODE-prompt}
      - AGIXT_ENABLE_SEARCHPARAM_CONFIG=${AGIXT_ENABLE_SEARCHPARAM_CONFIG}
      - AGIXT_CONVERSATION=${AGIXT_CONVERSATION}
      - AGIXT_CONVERSATION_MODE=${AGIXT_CONVERSATION_MODE}
      - INTERACTIVE_UI=${INTERACTIVE_UI}
      - AGIXT_AGENT=${AGIXT_AGENT-Software Engineer}
      - AGIXT_INSIGHT_AGENT=${AGIXT_INSIGHT_AGENT}
      - AGIXT_USE_SELECTED_AGENT=${AGIXT_USE_SELECTED_AGENT}
      - AGIXT_PROMPT_CATEGORY=${AGIXT_PROMPT_CATEGORY}
      - AGIXT_PROMPT_NAME=${AGIXT_PROMPT_NAME}
      - AGIXT_COMMAND=${AGIXT_COMMAND}
      - AGIXT_COMMAND_MESSAGE_ARGS=${AGIXT_COMMAND_MESSAGE_ARGS}
      - AGIXT_CHAIN_COMMANDS=${AGIXT_CHAIN_COMMANDS}
      - AGIXT_CHAIN_ARGS=${AGIXT_CHAIN_ARGS}
      - AGIXT_ALLOW_MESSAGE_EDITING=${AGIXT_ALLOW_MESSAGE_EDITING}
      - AGIXT_ALLOW_MESSAGE_DELETION=${AGIXT_ALLOW_MESSAGE_DELETION}
      - AGIXT_RLHF=${AGIXT_RLHF}
      - AGIXT_FILE_UPLOAD_ENABLED=${AGIXT_FILE_UPLOAD_ENABLED}
      - AGIXT_VOICE_INPUT_ENABLED=${AGIXT_VOICE_INPUT_ENABLED}
      - AGIXT_SHOW_APP_BAR=${AGIXT_SHOW_APP_BAR}
      - AGIXT_SHOW_SELECTION=${AGIXT_SHOW_SELECTION}
      - AGIXT_SHOW_CHAT_THEME_TOGGLES=${AGIXT_SHOW_CHAT_THEME_TOGGLES}
      - AGIXT_FOOTER_MESSAGE=${AGIXT_FOOTER_MESSAGE}
      - AGIXT_SHOW_OVERRIDE_SWITCHES=${AGIXT_SHOW_OVERRIDE_SWITCHES}
      - ADSENSE_ACCOUNT=${ADSENSE_ACCOUNT-ca-pub-7353611168636388}
      - STRIPE_PRICING_TABLE_ID=${STRIPE_PRICING_TABLE_ID}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - GRAVATAR_SECRET_KEY=${GRAVATAR_SECRET_KEY}
    ports:
      - 3437:3437
    restart: unless-stopped
