version: '3.7'
services:
  agixt-interactive:
    image: ghcr.io/jamesonrgrieve/agixt-interactive:main
    init: true
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - ADSENSE_ACCOUNT=${ADSENSE_ACCOUNT-ca-pub-7353611168636388}
      - AGIXT_AGENT=${AGIXT_AGENT-Software Engineer}
      - AGIXT_FILE_UPLOAD_ENABLED=${AGIXT_FILE_UPLOAD_ENABLED-true}
      - AGIXT_FOOTER_MESSAGE=${AGIXT_FOOTER_MESSAGE-Powered by AGiXT}
      - AGIXT_MODE=${AGIXT_MODE-prompt}
      - AGIXT_PROMPT_CATEGORY=${AGIXT_PROMPT_CATEGORY-Default}
      - AGIXT_PROMPT_NAME=${AGIXT_PROMPT_NAME-Persona Chat}
      - AGIXT_REQUIRE_API_KEY=${AGIXT_REQUIRE_API_KEY-false}
      - AGIXT_RLHF=${AGIXT_RLHF-true}
      - AGIXT_SERVER=${AGIXT_SERVER-http://localhost:7437}
      - AGIXT_SHOW_AGENT_BAR=${AGIXT_SHOW_AGENT_BAR-true}
      - AGIXT_SHOW_APP_BAR=${AGIXT_SHOW_APP_BAR-true}
      - APP_DESCRIPTION=${APP_DESCRIPTION-AGiXT Chat}
      - APP_NAME=${APP_NAME-AGiXT}
      - APP_URI=${APP_URI-http://localhost:3437}
      - LOG_VERBOSITY_SERVER=${LOG_VERBOSITY_SERVER-3}
      - THEME_NAME=${THEME_NAME-valentines}
      - ENV=${ENV-production}
      - TZ=${TZ-America/New_York}
    ports:
      - 3437:3437
    restart: unless-stopped
