version: '3.7'

services:
  agixt:
    image: ghcr.io/josh-xt/agixt:main
    init: true
    environment:
      DATABASE_TYPE: sqlite
      LOG_LEVEL: INFO
      DATABASE_NAME: models/agixt
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
      UVICORN_WORKERS: ${UVICORN_WORKERS:-5}
      AUTH_WEB: ${AUTH_WEB-http://nursegpt:3051/user}
      AGIXT_URI: ${AGIXT_URI-http://agixt:7437}
      AGIXT_API_KEY: ${ENCRYPTION_SECRET}
      DISABLED_PROVIDERS: ${DISABLED_PROVIDERS}
      WORKING_DIRECTORY: ${WORKING_DIRECTORY:-/agixt/WORKSPACE}
      REGISTRATION_DISABLED: ${REGISTRATION_DISABLED:-false}
      TOKENIZERS_PARALLELISM: "false"
      AUTH_PROVIDER: magicalauth
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      MICROSOFT_CLIENT_SECRET: ${MICROSOFT_CLIENT_SECRET}
      TZ: ${TZ-America/New_York}
    ports:
      - 9437:7437
    volumes:
      - ./models:/agixt/models
      - ./WORKSPACE:/agixt/WORKSPACE
      - ./memories:/agixt/memories
      - /var/run/docker.sock:/var/run/docker.sock
  boilerplate_web:
    image: ghcr.io/gt-umbrella/boilerplate_web:main
    init: true
    environment:
      MODE: ${MODE:-production}
      NEXT_TELEMETRY_DISABLED: 1
      AGIXT_AGENT: ${AGIXT_AGENT:-AGiXT}
      AGIXT_FOOTER_MESSAGE: ${AGIXT_FOOTER_MESSAGE:-AGiXT 2024}
      AGIXT_SERVER: ${AGIXT_SERVER:-https://api.app.agixt.chat}
      AGIXT_SHOW_AGENT_BAR: ${AGIXT_SHOW_AGENT_BAR-false}
      AGIXT_SHOW_APP_BAR: ${AGIXT_SHOW_APP_BAR-true}
      APP_DESCRIPTION: ${APP_DESCRIPTION-AGiXT is an advanced artificial intelligence agent orchestration agent.}
      APP_NAME: ${APP_NAME:-AGiXT}
      APP_URI: ${APP_URI:-https://app.agixt.chat}
      AUTH_WEB: ${AUTH_WEB:-https://app.agixt.chat/user}
      LOG_VERBOSITY_SERVER: ${LOG_VERBOSITY_SERVER:-3}
      AGIXT_FILE_UPLOAD_ENABLED: ${AGIXT_FILE_UPLOAD_ENABLED:-false}
      AGIXT_VOICE_INPUT_ENABLED: ${AGIXT_VOICE_INPUT_ENABLED:-true}
      AGIXT_REQUIRE_API_KEY: ${AGIXT_REQUIRE_API_KEY:-false}
      AGIXT_RLHF: ${AGIXT_RLHF:-true}
      AGIXT_ALLOW_MESSAGE_EDITING: ${AGIXT_ALLOW_MESSAGE_EDITING:-true}
      AGIXT_ALLOW_MESSAGE_DELETION: ${AGIXT_ALLOW_MESSAGE_DELETION:-true}
      AGIXT_SHOW_OVERRIDE_SWITCHES: ${AGIXT_SHOW_OVERRIDE_SWITCHES:-tts,websearch,analyze-user-input}
      AGIXT_SHOW_CHAT_THEME_TOGGLES: ${AGIXT_SHOW_CHAT_THEME_TOGGLES}
      AGIXT_SHOW_SELECTION: ${AGIXT_SHOW_SELECTION:-conversation,conversation}
      AGIXT_CONVERSATION_MODE: ${AGIXT_CONVERSATION_MODE:-select}
      INTERACTIVE_MODE: ${INTERACTIVE_MODE:-chat}
      THEME_NAME: ${THEME_NAME}
      ALLOW_EMAIL_SIGN_IN: ${ALLOW_EMAIL_SIGN_IN:-false}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      TZ: ${TZ:-America/New_York}
    ports:
      - "3051:3051"
    volumes:
      - ./node_modules:/app/node_modules
