version: '3.7'

services:
  xtsystems-web:
    image: ghcr.io/we-foresee-it/xtsystems_web:main
    init: true
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - AGIXT_AGENT=${AGIXT_AGENT-XT}
      - AGIXT_COMMAND=${AGIXT_COMMAND-}
      - AGIXT_COMMAND_MESSAGE_ARG=${AGIXT_COMMAND_MESSAGE_ARG-}
      - AGIXT_FILE_UPLOAD_ENABLED=${AGIXT_FILE_UPLOAD_ENABLED-false}
      - AGIXT_FOOTER_MESSAGE=${AGIXT_FOOTER_MESSAGE-XT Systems 2024}
      - AGIXT_MODE=${AGIXT_MODE-command}
      - AGIXT_REQUIRE_API_KEY=${AGIXT_REQUIRE_API_KEY-true}
      - AGIXT_SERVER=${AGIXT_SERVER-}
      - AGIXT_SHOW_AGENT_BAR=${AGIXT_SHOW_AGENT_BAR-false}
      - AGIXT_SHOW_APP_BAR=${AGIXT_SHOW_APP_BAR-true}
      - APP_DESCRIPTION=${APP_DESCRIPTION-XT Systems helps MSPs.}
      - APP_NAME=${APP_NAME-XT Systems}
      - APP_URI=${APP_URI-}
      - AUTH_WEB=${AUTH_WEB-}
      - LOG_VERBOSITY_SERVER=${LOG_VERBOSITY_SERVER-3}
      - TZ=${TZ-America/New_York}
    ports:
      - '3051:3051'
