name: Dev Branch Docker Build
on:
  push:
    branches-ignore:
      - main
env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Extract GitHub info and ensure lowercase
        id: extract_info
        run: |
          echo "repo_name=$(echo ${{ github.repository }} | cut -d'/' -f 2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "org_name=$(echo ${{ github.repository }} | cut -d'/' -f 1 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "branch_name=$(echo ${{ github.ref }} | cut -d'/' -f 3 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.1.0
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            ${{ env.REGISTRY }}/${{ steps.extract_info.outputs.org_name }}/${{ steps.extract_info.outputs.repo_name }}:${{ steps.extract_info.outputs.branch_name }}