name: Lint Trigger

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  call-reusable-lint:
    name: Call Reusable Lint Workflow
    uses: JamesonRGrieve/Workflows/.github/workflows/test-ts-lint.yml@main
    with:
      lint_command: npm run lint
      fix_command: npm run lint-fix
