name: Lint
on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-22.04
    name: TypeScript ESLint Check
    outputs:
      auto_formatted: ${{ steps.push-changes.outputs.pushed }}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ github.token }}
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci

      - name: Run Lint on files
        id: lint-check
        continue-on-error: true
        run: npm run lint && npm run prettier

      - name: Auto-format with ESLint and Prettier
        id: format
        if: steps.lint-check.outcome == 'failure'
        continue-on-error: true
        run: npm run fix

      - name: Configure Git
        if: steps.lint-check.outcome == 'failure'
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions-user@users.noreply.github.com"

      - name: Commit and push changes
        id: push-changes
        if: steps.lint-check.outcome == 'failure'
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "pushed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "style: auto-format Python code with black"
            git push
            echo "pushed=true" >> $GITHUB_OUTPUT
          fi

      - name: Fail the workflow if formatting was needed
        if: steps.lint-check.outcome == 'failure' && steps.push-changes.outputs.pushed == 'true'
        run: |
          echo "Code was auto-formatted. A new commit has been pushed with the changes."
          echo "This workflow is failing intentionally to trigger a new run with formatted code."
          exit 0

# TODO Change this to 1 when linting passes.
