name: Push Main Branch to Target Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Push main to target repository
        env:
          TARGET_REPO: ${{ secrets.SECRET_TARGET }}
          GITHUB_TOKEN: ${{ secrets.SECRET_PAT }}
        run: |
          # Extract org/repo if full URL was provided
          if [[ "$TARGET_REPO" == *"github.com"* ]]; then
            TARGET_REPO=$(echo "$TARGET_REPO" | sed 's/.*github.com[\/:]\(.*\)\.git*/\1/' | sed 's/\.git$//')
          fi
          
          # Remove any trailing .git if present
          TARGET_REPO=$(echo "$TARGET_REPO" | sed 's/\.git$//')
          
          echo "Using repository: ${TARGET_REPO}"
          
          # Test git clone access
          echo "Testing git clone access..."
          if git ls-remote "https://${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git" > /dev/null 2>&1; then
            echo "Git repository access verified"
          else
            echo "Error: Cannot access git repository. Please verify:"
            echo "1. The repository exists and is spelled correctly"
            echo "2. The PAT has correct permissions"
            echo "3. The PAT is properly formatted"
            echo "Try running: git clone https://[PAT]@github.com/${TARGET_REPO}.git manually to test"
            exit 1
          fi
          
          # Add the target repository as a remote
          echo "Adding remote..."
          REMOTE_URL="https://${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git"
          git remote add target "$REMOTE_URL"
          
          # Print remotes (safely)
          echo "Configured remotes:"
          git remote -v | sed 's/https:\/\/.*@/https:\/\/***@/'
          
          # Push only the main branch
          echo "Pushing to main branch..."
          git push target main:main