name: Push Main Branch to Target Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Push main to target repository
        env:
          TARGET_REPO: ${{ secrets.SECRET_TARGET }}
          GITHUB_TOKEN: ${{ secrets.SECRET_PAT }}
        run: |
          # Debug check (safely)
          echo "Target repo format analysis:"
          echo "Length of TARGET_REPO: ${#TARGET_REPO}"
          echo "Number of slashes: $(echo $TARGET_REPO | tr -cd '/' | wc -c)"
          echo "Contains http: $(echo $TARGET_REPO | grep -c 'http')"
          echo "Contains github.com: $(echo $TARGET_REPO | grep -c 'github.com')"
          echo "Pattern check: $(echo $TARGET_REPO | sed 's/[^a-zA-Z0-9\/_-]/#/g')"
          
          # Extract org/repo if full URL was provided
          if [[ "$TARGET_REPO" == *"github.com"* ]]; then
            TARGET_REPO=$(echo "$TARGET_REPO" | sed 's/.*github.com[\/:]\(.*\)\.git/\1/' | sed 's/\.git$//')
            echo "Extracted org/repo format: $(echo $TARGET_REPO | sed 's/[^a-zA-Z0-9\/_-]/#/g')"
          fi
          
          # Verify format
          if [[ ! "$TARGET_REPO" =~ ^[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+$ ]]; then
            echo "Error: TARGET_REPO format is incorrect. Should be 'org/repo'"
            exit 1
          fi
          
          # Add the target repository as a remote
          echo "Adding remote..."
          REMOTE_URL="https://${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git"
          
          git remote add target "$REMOTE_URL"
          
          # Print remotes (safely)
          echo "Configured remotes:"
          git remote -v | sed 's/https:\/\/.*@/https:\/\/***@/'
          
          # Push only the main branch
          echo "Pushing to main branch..."
          git push target main:main