name: Push Main Branch to Target Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Push to target repository
        env:
          TARGET_REPO: ${{ secrets.SECRET_TARGET }}
          GITHUB_TOKEN: ${{ secrets.SECRET_PAT }}
        run: |
          # Extract org/repo if full URL was provided
          if [[ "$TARGET_REPO" == *"github.com"* ]]; then
            TARGET_REPO=$(echo "$TARGET_REPO" | sed 's/.*github.com[\/:]\(.*\)\.git*/\1/' | sed 's/\.git$//')
          fi

          # Remove any trailing .git if present
          TARGET_REPO=$(echo "$TARGET_REPO" | sed 's/\.git$//')

          echo "Using repository: ${TARGET_REPO}"

          # Setup git credentials
          git config --global credential.helper store
          echo "https://oauth2:${GITHUB_TOKEN}@github.com" > ~/.git-credentials

          # Add remote and push
          git remote add target "https://github.com/${TARGET_REPO}.git"
          git push target main:main
