name: Push Main Branch to Target Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Push main to target repository
        env:
          TARGET_REPO: ${{ secrets.SECRET_TARGET }}
          GITHUB_TOKEN: ${{ secrets.SECRET_PAT }}
        run: |
          # Extract org/repo if full URL was provided
          if [[ "$TARGET_REPO" == *"github.com"* ]]; then
            TARGET_REPO=$(echo "$TARGET_REPO" | sed 's/.*github.com[\/:]\(.*\)\.git*/\1/' | sed 's/\.git$//')
          fi
          
          # Remove any trailing .git if present
          TARGET_REPO=$(echo "$TARGET_REPO" | sed 's/\.git$//')
          
          echo "Using repository: ${TARGET_REPO}"
          
          # Test repository access
          echo "Testing repository access..."
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${GITHUB_TOKEN}" \
            "https://api.github.com/repos/${TARGET_REPO}")
          
          if [ "$HTTP_CODE" == "404" ]; then
            echo "Error: Cannot access repository ${TARGET_REPO}"
            echo "Please verify the PAT has 'repo' access to this repository"
            exit 1
          elif [ "$HTTP_CODE" != "200" ]; then
            echo "Error: Unexpected response from GitHub API (HTTP ${HTTP_CODE})"
            exit 1
          fi
          
          # Add the target repository as a remote
          echo "Adding remote..."
          REMOTE_URL="https://${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git"
          git remote add target "$REMOTE_URL"
          
          # Print remotes (safely)
          echo "Configured remotes:"
          git remote -v | sed 's/https:\/\/.*@/https:\/\/***@/'
          
          # Push only the main branch
          echo "Pushing to main branch..."
          git push target main:main